2023-11-16 10:27:19,249 - ERROR - Image file not found for [Errno 2] No such file or directory: 'C:\\Users\\iangs\\repos\\HR-pQCT-Image-Processing-Server\\d0016410_eval_ml_segmentation.yaml'
2023-11-16 10:28:58,468 - ERROR - Image file not found for [Errno 2] No such file or directory: 'C:\\Users\\iangs\\repos\\HR-pQCT-Image-Processing-Server\\d0016410_eval_ml_segmentation.yaml'
2023-11-16 15:12:37,453 - ERROR - FileNotFoundError: Path to bl_torch python executable does not exist
2023-11-16 15:14:02,642 - ERROR - FileNotFoundError: Path to bl_torch python executable does not exist
2023-11-16 17:21:24,430 - ERROR - FileNotFoundError: Path to bl_torch python executable does not exist
2023-11-16 17:22:25,335 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:22:25,337 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 72, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 94, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 112, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 17:27:04,596 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:27:04,599 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 72, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 94, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 112, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 17:40:24,068 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:40:24,070 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 72, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 94, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 112, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 17:54:03,656 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:54:03,658 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 73, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 96, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 114, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 17:54:54,893 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:54:54,895 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 73, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 96, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 114, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 17:56:45,917 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:56:45,919 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 72, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 95, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 113, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 17:59:04,844 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 17:59:04,846 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 72, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 95, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 113, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 18:00:33,755 - ERROR - Transfer to D0016410.AIM of EMILY.UCALGARY.CA failed: Error Image masks not found in masks dir
2023-11-16 18:00:33,756 - ERROR - Traceback (most recent call last):
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 72, in send
    self._get_send_for_job()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 95, in _get_send_for_job
    self._send_radius_tibia_final()
  File "C:\Users\iangs\repos\HR-pQCT-Image-Processing-Server\send.py", line 113, in _send_radius_tibia_final
    raise FileNotFoundError("Image masks not found in masks dir")
FileNotFoundError: Image masks not found in masks dir

2023-11-16 18:01:03,126 - ERROR - FileNotFoundError: Path to bl_torch python executable does not exist
